name: Run MoQabot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Debugging Environment Variables
      run: |
        echo "WIKI_USERNAME is set to ${{ secrets.WIKI_USERNAME }}"
        echo "Checking other secrets..."

    - name: Run MoQabot
      env:
        WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
        WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
      run: |
        python wikipedia_stub_bot.py
